### ISSUE TITLE
Error in LSTM-Sunpots-tn_b.ipynb 

### ISSUE THREAD

**Issue by MohamedNedal** [brewersey/sunspots#1]
Hello, 
I was trying the file 

> LSTM-Sunpots-tn_b.ipynb 

and I got this error: 

> ValueError: 'Date' is both an index level and a column label, which is ambiguous. 

at this line 
`sunspots_day.sort_values('Date', ascending=True, inplace = True) 
`

Can you please tell how to fix this? 

Thanks in advance, 
Mohamed

**Comment by brewersey** [comment]
Hi Mohamed,
Commenting out the lines where the index is labeled should solve the problem.
For example where you see something like:
sunspots_day.index = sunspots_day.Date

Change it to:
#sunspots_day.index = sunspots_day.Date

Hope this helps

**Comment by MohamedNedal** [comment]
Thank you very much, it works.
